---
title: चमकता हुआ पदक
hero_image: images/banner.png
description: एक महसूस करने वाला पदक बनाएं जो रोशनीरोशन होता है, और इलेक्ट्रॉनिक सर्किट (electronic circuits) के बारे में सीखें
theme: violet
version: 3.0.0
listed: true
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-0, manufacture-1, community-0
interests: wearable-technology
technologies: electronic-components
site_areas: coderdojo, projects
hardware: electronic-components
software: ''
last_tested: "2017-04-28"
steps:
  - 
    title: परिचय
  - 
    title: Make a circuit
  - 
    title: Add a switch
  - 
    title: Sew on components
  - 
    title: Complete your wearable circuit
  - 
    title: Add more LEDs
  - 
    title: Make detachable parts
