---
title: Insigne lumineux
hero_image: images/banner.png
description: Fabriquer un insigne en feutre qui s'allume et découvrir les circuits
  électroniques
theme: violet
version: 3.0.0
listed: true
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-0, manufacture-1, community-0
interests: wearable-technology
technologies: electronic-components
site_areas: coderdojo, projects
hardware: electronic-components
software: ''
last_tested: '2017-04-28'
steps:
- title: Introduction
  completion: engaged
- title: Créer un circuit
- title: Ajouter un commutateur
- title: Coudre des composants
- title: Compléter ton circuit portable
- title: Ajouter plus de LED
  completion: internal
- title: Créer des pièces détachables
